package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.StockLogDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StockLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 02 14:59:08 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 02 14:59:08 GMT+08:00 2020
     */
    int insert(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 02 14:59:08 GMT+08:00 2020
     */
    int insertSelective(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 02 14:59:08 GMT+08:00 2020
     */
    StockLogDO selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 02 14:59:08 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 02 14:59:08 GMT+08:00 2020
     */
    int updateByPrimaryKey(StockLogDO record);
}